#!/bin/bash

# STEP 3 — REAL RUNTIME VALIDATION
# This script monitors bot logs while you test in WhatsApp

echo "=========================================="
echo "STEP 3 — REAL RUNTIME VALIDATION"
echo "=========================================="
echo ""
echo "📋 Instructions:"
echo ""
echo "1. Open the WhatsApp chat with Nexa"
echo "2. For EACH test below:"
echo "   a. Complete the action in WhatsApp"
echo "   b. Watch this terminal for logs"
echo "   c. Look for [DocStore] messages"
echo ""
echo "=========================================="
echo "🔴 REAL TEST 1 — Send actual PDF"
echo "=========================================="
echo ""
echo "Action:"
echo "  → Send a PDF file to Nexa (no message, just file)"
echo ""
echo "Expected logs:"
echo "  [DocStore] PDF detected, extracting text..."
echo "  [DocStore] ✅ PDF stored and ready for summarize"
echo ""
echo "Press ENTER when you've sent the PDF..."
read

echo ""
echo "=========================================="
echo "🔴 REAL TEST 2 — Direct summarize"
echo "=========================================="
echo ""
echo "Action:"
echo "  → Send: @nexa summarize this pdf"
echo ""
echo "Expected logs:"
echo "  [executeIntent] ✅ PDF summarized"
echo ""
echo "Expected WhatsApp:"
echo "  → Summary message appears (no errors)"
echo ""
echo "Press ENTER when done..."
read

echo ""
echo "=========================================="
echo "🔴 REAL TEST 3 — Reply-based summarize"
echo "=========================================="
echo ""
echo "Action:"
echo "  1. Send ANOTHER PDF"
echo "  2. Wait for storage log"
echo "  3. Reply to that PDF message:"
echo "     @nexa summarize this"
echo ""
echo "Expected logs:"
echo "  [DocStore] PDF detected, extracting..."
echo "  [DocStore] ✅ PDF stored"
echo "  [executeIntent] ✅ PDF summarized"
echo ""
echo "Expected WhatsApp:"
echo "  → Summary appears (same as Test 2)"
echo ""
echo "Press ENTER when done..."
read

echo ""
echo "=========================================="
echo "🔴 REAL TEST 4 — Replace document"
echo "=========================================="
echo ""
echo "Action:"
echo "  1. Send PDF A"
echo "  2. Wait for [DocStore] ✅ Saved log"
echo "  3. Send @nexa summarize (get summary of A)"
echo "  4. Send PDF B (different file)"
echo "  5. Wait for [DocStore] ✅ Saved log"
echo "  6. Send @nexa summarize"
echo ""
echo "Expected:"
echo "  → Test 3 summary = from PDF A"
echo "  → Test 6 summary = from PDF B (different!)"
echo ""
echo "Press ENTER when done..."
read

echo ""
echo "=========================================="
echo "🔴 REAL TEST 5 — Fresh bot (reset test)"
echo "=========================================="
echo ""
echo "Action:"
echo "  1. Restart the bot: Ctrl+C below then 'npm start'"
echo "  2. Wait for 'Client is ready' message"
echo "  3. Send: @nexa summarize this pdf"
echo ""
echo "Expected logs:"
echo "  [DocStore] ❌ No document found"
echo ""
echo "Expected WhatsApp:"
echo "  → \"No PDF found. Please send a document to summarize.\""
echo ""
echo "=========================================="
echo ""
echo "✅ All tests completed!"
echo "Copy logs from terminal window and paste below."
echo ""
